# -*- coding: utf-8 -*-
"""automate_ZikriAbdilah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E9nA0jHmlgDF54MAfKdrHdCMPLphUEGR
"""

import pandas as pd
import os
from sklearn.preprocessing import LabelEncoder

def preprocess_dataset(input_path, output_path):
    # Load data
    df = pd.read_csv("bestSelling_games.csv")

    # Ubah tanggal
    df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

    # Drop kolom tidak penting
    df_clean = df.drop(columns=['user_defined_tags', 'other_features', 'supported_languages'])

    # Isi missing values
    for col in ['rating', 'release_date']:
        if df_clean[col].isnull().sum() > 0:
            if df_clean[col].dtype == 'float64':
                df_clean[col] = df_clean[col].fillna(df_clean[col].mean())
            else:
                df_clean[col] = df_clean[col].fillna(method='ffill')

    # Encode kategorikal
    label_cols = ['developer', 'supported_os']
    le = LabelEncoder()
    for col in label_cols:
        df_clean[col] = le.fit_transform(df_clean[col])

    # Simpan hasil
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df_clean.to_csv(output_path, index=False)
    print(f"✅ Preprocessed dataset saved to {output_path}")

if __name__ == '__main__':
    preprocess_dataset(
        input_path='../namadataset_raw/bestSelling_games.csv',
        output_path='namadataset_preprocessing/bestSelling_games_clean.csv'
    )